baseUrl = https://sit-agroadmin.mjunction.in/pre-auth/agro/login
browser = chrome
username = UAT.TEST.manmeet.singh
password = Pass@123
otp = 100000
LoginUsername = Manmeet Singh
devMode=true
BidderLoginUrl = https://sit-agro.mjunction.in/login
bidder1Name = Manmeet Demo
bidder1LoginName = 61000105
bidder1LoginPassword = Pass@8319061655